# uncomment annotations to make this as default StorageClass
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: dynamic-nfs-storage-provisioner
#  annotations:
#    storageclass.kubernetes.io/is-default-class: "true"  
provisioner: example.com/nfs
parameters:
  archiveOnDelete: "false"
