apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pvc
spec:
  storageClassName: dynamic-nfs-storage-provisioner
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
